export default [
  { name: 'img_01', type: 'texture', path: '/textures/img_01.jpg' },
  { name: 'img_02', type: 'texture', path: '/textures/img_02.jpg' },
  { name: 'img_03', type: 'texture', path: '/textures/img_03.jpg' },
  { name: 'img_04', type: 'texture', path: '/textures/img_04.jpg' },
  { name: 'img_05', type: 'texture', path: '/textures/img_05.jpg' },
  { name: 'img_06', type: 'texture', path: '/textures/img_06.jpg' },
  { name: 'img_07', type: 'texture', path: '/textures/img_07.jpg' },
  { name: 'img_08', type: 'texture', path: '/textures/img_08.jpg' },
  { name: 'img_09', type: 'texture', path: '/textures/img_09.jpg' },
  { name: 'img_10', type: 'texture', path: '/textures/img_10.jpg' },
  { name: 'img_11', type: 'texture', path: '/textures/img_11.jpg' },
  { name: 'img_12', type: 'texture', path: '/textures/img_12.jpg' },
  { name: 'img_13', type: 'texture', path: '/textures/img_13.jpg' },
  { name: 'img_14', type: 'texture', path: '/textures/img_14.jpg' },
  { name: 'img_15', type: 'texture', path: '/textures/img_15.jpg' },
  { name: 'img_16', type: 'texture', path: '/textures/img_16.jpg' },
  { name: 'img_17', type: 'texture', path: '/textures/img_17.jpg' },
  { name: 'img_18', type: 'texture', path: '/textures/img_18.jpg' },
  { name: 'img_19', type: 'texture', path: '/textures/img_19.jpg' },
  { name: 'img_20', type: 'texture', path: '/textures/img_20.jpg' },
  { name: 'img_21', type: 'texture', path: '/textures/img_21.jpg' },
  { name: 'img_22', type: 'texture', path: '/textures/img_22.jpg' },
];
